[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
goraffle = "EyanJkk7BV9nA5ZzuBQLqC3FWf25dLdgbURhLiV3Hc31"
junkpusher = "5gJkp3DsVTtBP6k7WtbiNBjQhAESgGrgu6AJfypMCAwe"
gorbagio_migration = "3PtknVekKAYAYExL6YQWxf6bycpGWoQQ9tNM566qzKmU"
gorbagio_marketplace = "DohoM3SvQzfcHVWH1r6BVTWdcNgYQxsxsTqxeZWBmL2E"
nft_launchpad = "9CzjUboaFZtUhtkqVN2wgWEunDasdorwo6CJfYrJWngj"

[programs.mainnet]
nft_launchpad = "9CzjUboaFZtUhtkqVN2wgWEunDasdorwo6CJfYrJWngj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.trashscan.io"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
